[package]
name = "hint_tool"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
blockifier = { workspace = true }
cairo-vm = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starknet-os = { path = "../../starknet-os" }

[[bin]]
name = "hint_tool"
path = "src/main.rs"
