name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup show
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    env:
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-19
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-19
      TABLEGEN_190_PREFIX: /usr/lib/llvm-19
    steps:
      - uses: actions/checkout@v3
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install LLVM/MLIR 19 for cairo-native
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-19 \
            llvm-19-dev \
            llvm-19-runtime \
            clang-19 \
            clang-tools-19 \
            libclang-19-dev \
            lld-19 \
            libpolly-19-dev \
            libmlir-19-dev \
            mlir-19-tools
      - name: "Install Python dependencies"
        run: |
          pip install -r requirements.txt
      - run: cargo clippy --all --all-targets -- -D warnings

  tests:
    runs-on: ubuntu-latest
    env:
      SNOS_RPC_URL: ${{ secrets.SNOS_RPC_URL }}
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-19
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-19
      TABLEGEN_190_PREFIX: /usr/lib/llvm-19
    steps:
      - uses: actions/checkout@v3
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install LLVM/MLIR 19 for cairo-native
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-19 \
            llvm-19-dev \
            llvm-19-runtime \
            clang-19 \
            clang-tools-19 \
            libclang-19-dev \
            lld-19 \
            libpolly-19-dev \
            libmlir-19-dev \
            mlir-19-tools
      - name: "Install Python dependencies"
        run: |
          pip install -r requirements.txt
      - name: "Run tests"
        run: |
          make test-workspace

  udeps:
    runs-on: ubuntu-latest
    if: false # Skipping the unused dependency test for now
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: rustup install nightly-2024-09-05
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: "Install Python dependencies"
        run: |
          pip install -r requirements.txt
      - run: cargo +nightly-2024-09-05 install cargo-udeps@0.1.54 --locked
      - run: cargo +nightly-2024-09-05 udeps --all-targets
