on: [push, pull_request]

name: Sn os
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Toolchain Setup
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - name: Check format
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Toolchain Setup
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - name: Check lint
        run: cargo clippy
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Toolchain Setup
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: pip install cairo-lang; cargo test
